vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            # le dossier dans lequel est envoi l'image
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

#ce package est créé lors du require vich.... pour la gestion d'image
# le namer est une clef unique qui permet de supprimer la image quand je la remplace 

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
